"""drop bot_state and auction_bids

Both tables were written only by ``lineup.py`` and ``auction.py``, deleted earlier in
this phase, and neither ever held a row.

**The proof, run against the working database immediately before this revision was
written** (SPEC's rule: no DROP without a verified SELECT)::

    select 'bot_state' as t, count(*) from bot_state
    union all select 'auction_bids', count(*) from auction_bids;

     t            | count
    --------------+-------
     bot_state    |     0
     auction_bids |     0

So nothing is lost, and ``downgrade`` recreates both in full -- columns, defaults,
the three check constraints, the foreign key and the composite index -- rather than
leaving a one-way door. It restores empty tables, which is exactly what it removed.

Revision ID: 1942efd6a2dc
Revises: 7da5539562c0
Create Date: 2026-08-30

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1942efd6a2dc'
down_revision: Union[str, Sequence[str], None] = '7da5539562c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auction_bids_session_role'), table_name='auction_bids')
    op.drop_table('auction_bids')
    op.drop_table('bot_state')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_state',
    sa.Column('league_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('last_lineup_matchday', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('last_auction_session_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('league_id', name=op.f('pk_bot_state'))
    )
    op.create_table('auction_bids',
    sa.Column('league_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('placed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('amount', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('outcome', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('price', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("outcome = ANY (ARRAY['pending'::text, 'won'::text, 'lost'::text])", name=op.f('ck_auction_bids_outcome')),
    sa.CheckConstraint("role::text = ANY (ARRAY['P'::character varying, 'D'::character varying, 'C'::character varying, 'A'::character varying]::text[])", name=op.f('ck_auction_bids_role')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_auction_bids_amount_positive')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_auction_bids_player_id_players')),
    sa.PrimaryKeyConstraint('league_id', 'session_id', 'player_id', 'placed_at', name=op.f('pk_auction_bids'))
    )
    op.create_index(op.f('ix_auction_bids_session_role'), 'auction_bids', ['league_id', 'session_id', 'role'], unique=False)
    # ### end Alembic commands ###
