"""add qi_bias table

Revision ID: 2c01d7f58c06
Revises: 63cdd639f060
Create Date: 2026-08-26 07:00:25.542692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c01d7f58c06'
down_revision: Union[str, Sequence[str], None] = '63cdd639f060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qi_bias',
    sa.Column('stagione', sa.String(length=7), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('listone', sa.String(length=7), nullable=False),
    sa.Column('squadra', sa.String(length=3), nullable=False),
    sa.Column('ruoli_codice', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('qi', sa.SmallInteger(), nullable=False),
    sa.Column('qa', sa.SmallInteger(), nullable=False),
    sa.Column('fvm', sa.SmallInteger(), nullable=False),
    sa.Column('delta', sa.SmallInteger(), nullable=False),
    sa.Column('pct_delta', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("listone IN ('classic', 'mantra')", name=op.f('ck_qi_bias_listone')),
    sa.CheckConstraint('delta = qa - qi', name=op.f('ck_qi_bias_delta_is_derived')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_qi_bias_player_id_players')),
    sa.ForeignKeyConstraint(['stagione', 'squadra'], ['teams.stagione', 'teams.codice'], name=op.f('fk_qi_bias_stagione_squadra_teams')),
    sa.PrimaryKeyConstraint('stagione', 'player_id', 'listone', name=op.f('pk_qi_bias'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qi_bias')
    # ### end Alembic commands ###
