"""add aste tables

Revision ID: 392df537e31d
Revises: 22504ea43086
Create Date: 2026-08-27 08:43:38.469846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '392df537e31d'
down_revision: Union[str, Sequence[str], None] = '22504ea43086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asta',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('db_shard', sa.Text(), nullable=False),
    sa.Column('asta_type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('num_teams', sa.Integer(), nullable=True),
    sa.Column('num_credits', sa.Integer(), nullable=True),
    sa.Column('min_player', sa.Integer(), nullable=True),
    sa.Column('max_player', sa.Integer(), nullable=True),
    sa.Column('asta_mode', sa.Text(), nullable=True),
    sa.Column('raise_mode', sa.Text(), nullable=True),
    sa.Column('counter_time', sa.Integer(), nullable=True),
    sa.Column('counter_time_first', sa.Integer(), nullable=True),
    sa.Column('call_at_quotaz', sa.Boolean(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asta'))
    )
    op.create_index('ix_asta_asta_type', 'asta', ['asta_type'], unique=False)
    op.create_table('asta_assignment',
    sa.Column('asta_id', sa.Text(), nullable=False),
    sa.Column('player_uuid', sa.Text(), nullable=False),
    sa.Column('fantacalcio_id', sa.BigInteger(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('buyer_team_id', sa.Text(), nullable=True),
    sa.Column('closed_at_ms', sa.BigInteger(), nullable=True),
    sa.Column('ladder', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asta_id'], ['asta.id'], name=op.f('fk_asta_assignment_asta_id_asta'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fantacalcio_id'], ['players.id'], name=op.f('fk_asta_assignment_fantacalcio_id_players')),
    sa.PrimaryKeyConstraint('asta_id', 'player_uuid', name=op.f('pk_asta_assignment')),
    sa.UniqueConstraint('asta_id', 'player_uuid', name='uq_asta_assignment_asta_id_player_uuid')
    )
    op.create_index('ix_asta_assignment_fantacalcio_id', 'asta_assignment', ['fantacalcio_id'], unique=False)
    op.create_table('asta_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asta_id', sa.Text(), nullable=False),
    sa.Column('last_update', sa.BigInteger(), nullable=True),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_type', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asta_id'], ['asta.id'], name=op.f('fk_asta_event_asta_id_asta'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asta_event'))
    )
    op.create_index('ix_asta_event_asta_id_seen_at', 'asta_event', ['asta_id', 'seen_at'], unique=False)
    op.create_index('uq_asta_event_asta_id_last_update', 'asta_event', ['asta_id', 'last_update'], unique=True, postgresql_where=sa.text('last_update IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_asta_event_asta_id_last_update', table_name='asta_event', postgresql_where=sa.text('last_update IS NOT NULL'))
    op.drop_index('ix_asta_event_asta_id_seen_at', table_name='asta_event')
    op.drop_table('asta_event')
    op.drop_index('ix_asta_assignment_fantacalcio_id', table_name='asta_assignment')
    op.drop_table('asta_assignment')
    op.drop_index('ix_asta_asta_type', table_name='asta')
    op.drop_table('asta')
    # ### end Alembic commands ###
