"""add league snapshot tables

Revision ID: 556b2f07b3cf
Revises: 77ba7a89c408
Create Date: 2026-08-26 07:45:07.785762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '556b2f07b3cf'
down_revision: Union[str, Sequence[str], None] = '77ba7a89c408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_player_pool',
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('quotazione', sa.SmallInteger(), nullable=True),
    sa.Column('fvm_classic', sa.Integer(), nullable=True),
    sa.Column('fvm_mantra', sa.Integer(), nullable=True),
    sa.Column('ruoli_codice', sa.ARRAY(sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('captured_at', 'league_id', 'player_id', name=op.f('pk_league_player_pool'))
    )
    op.create_table('league_snapshot',
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=False),
    sa.Column('competition_id', sa.BigInteger(), nullable=True),
    sa.Column('season_id', sa.SmallInteger(), nullable=True),
    sa.Column('matchday', sa.SmallInteger(), nullable=True),
    sa.Column('matchday_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('budget', sa.SmallInteger(), nullable=True),
    sa.Column('roster_size', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('captured_at', 'league_id', name=op.f('pk_league_snapshot'))
    )
    op.create_table('league_team_snapshot',
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('owner', sa.Text(), nullable=False),
    sa.Column('credits_initial', sa.SmallInteger(), nullable=True),
    sa.Column('credits_spent', sa.SmallInteger(), nullable=True),
    sa.Column('credits_remaining', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('captured_at', 'league_id', 'team_id', name=op.f('pk_league_team_snapshot'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('league_team_snapshot')
    op.drop_table('league_snapshot')
    op.drop_table('league_player_pool')
    # ### end Alembic commands ###
