"""player_exclusion: players who have left the league

Revision ID: 5839418913d5
Revises: d3f81a6b2e50
Create Date: 2026-08-31 07:52:36.859786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5839418913d5'
down_revision: Union[str, Sequence[str], None] = 'd3f81a6b2e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_exclusion',
    sa.Column('player_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('player_id', name=op.f('pk_player_exclusion'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_exclusion')
    # ### end Alembic commands ###
