"""add player_sentiment table

Revision ID: 5c4b935af8ff
Revises: ca3bb72a7a16
Create Date: 2026-08-26 07:15:19.510927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c4b935af8ff'
down_revision: Union[str, Sequence[str], None] = 'ca3bb72a7a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_sentiment',
    sa.Column('data_run', sa.Date(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('giorni_lookback', sa.SmallInteger(), nullable=False),
    sa.Column('stagione', sa.Text(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('squadra', sa.Text(), nullable=False),
    sa.Column('ruolo', sa.Text(), nullable=False),
    sa.Column('ruoli_mantra', sa.Text(), nullable=False),
    sa.Column('ruolo_campo', sa.Text(), nullable=False),
    sa.Column('deriva_ruolo', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('sentiment', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('disponibilita', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('titolarita', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('mercato', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('forma', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('rigorista', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('piazzati', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('confidenza', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('riassunto', sa.Text(), nullable=False),
    sa.Column('n_fonti', sa.SmallInteger(), nullable=False),
    sa.Column('fonti', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('modello', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_sentiment_player_id_players')),
    sa.PrimaryKeyConstraint('data_run', 'player_id', name=op.f('pk_player_sentiment'))
    )
    op.create_index('ix_player_sentiment_data_run_deriva', 'player_sentiment', ['data_run', 'deriva_ruolo'], unique=False)
    op.create_index('ix_player_sentiment_player', 'player_sentiment', ['player_id', 'data_run'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_player_sentiment_player', table_name='player_sentiment')
    op.drop_index('ix_player_sentiment_data_run_deriva', table_name='player_sentiment')
    op.drop_table('player_sentiment')
    # ### end Alembic commands ###
