"""add statistiche table

Revision ID: 63cdd639f060
Revises: befac71117d1
Create Date: 2026-08-26 06:58:16.656901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63cdd639f060'
down_revision: Union[str, Sequence[str], None] = 'befac71117d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistiche',
    sa.Column('stagione', sa.String(length=7), nullable=False),
    sa.Column('fonte', sa.String(length=12), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('listone', sa.String(length=7), nullable=False),
    sa.Column('squadra', sa.String(length=3), nullable=False),
    sa.Column('ruoli_codice', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('ruoli', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('partite_giocate', sa.SmallInteger(), nullable=False),
    sa.Column('media_voto', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('media_fantavoto', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('gol', sa.SmallInteger(), nullable=False),
    sa.Column('gol_subiti', sa.SmallInteger(), nullable=False),
    sa.Column('rigori_segnati', sa.SmallInteger(), nullable=False),
    sa.Column('rigori_tirati', sa.SmallInteger(), nullable=False),
    sa.Column('rigori_parati', sa.SmallInteger(), nullable=False),
    sa.Column('assist', sa.SmallInteger(), nullable=False),
    sa.Column('ammonizioni', sa.SmallInteger(), nullable=False),
    sa.Column('espulsioni', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("fonte IN ('fantacalcio', 'italia', 'statistico')", name=op.f('ck_statistiche_fonte')),
    sa.CheckConstraint("listone IN ('classic', 'mantra')", name=op.f('ck_statistiche_listone')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_statistiche_player_id_players')),
    sa.ForeignKeyConstraint(['stagione', 'squadra'], ['teams.stagione', 'teams.codice'], name=op.f('fk_statistiche_stagione_squadra_teams')),
    sa.PrimaryKeyConstraint('stagione', 'fonte', 'player_id', 'listone', name=op.f('pk_statistiche'))
    )
    op.create_index('ix_statistiche_stagione_player', 'statistiche', ['stagione', 'player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_statistiche_stagione_player', table_name='statistiche')
    op.drop_table('statistiche')
    # ### end Alembic commands ###
