"""add auction_bids table

Revision ID: 77ba7a89c408
Revises: 9a6db2706b72
Create Date: 2026-08-26 07:38:59.343824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ba7a89c408'
down_revision: Union[str, Sequence[str], None] = '9a6db2706b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_bids',
    sa.Column('league_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('role', sa.String(length=1), nullable=False),
    sa.Column('amount', sa.SmallInteger(), nullable=False),
    sa.Column('outcome', sa.Text(), server_default='pending', nullable=False),
    sa.Column('price', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IN ('pending', 'won', 'lost')", name=op.f('ck_auction_bids_outcome')),
    sa.CheckConstraint("role IN ('P', 'D', 'C', 'A')", name=op.f('ck_auction_bids_role')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_auction_bids_amount_positive')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_auction_bids_player_id_players')),
    sa.PrimaryKeyConstraint('league_id', 'session_id', 'player_id', 'placed_at', name=op.f('pk_auction_bids'))
    )
    op.create_index('ix_auction_bids_session_role', 'auction_bids', ['league_id', 'session_id', 'role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auction_bids_session_role', table_name='auction_bids')
    op.drop_table('auction_bids')
    # ### end Alembic commands ###
