"""add bot_state table

Revision ID: 9a6db2706b72
Revises: 5c4b935af8ff
Create Date: 2026-08-26 07:37:13.799011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a6db2706b72'
down_revision: Union[str, Sequence[str], None] = '5c4b935af8ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_state',
    sa.Column('league_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('last_lineup_matchday', sa.SmallInteger(), nullable=True),
    sa.Column('last_auction_session_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('league_id', name=op.f('pk_bot_state'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_state')
    # ### end Alembic commands ###
