"""add teams table

Revision ID: b4ed89e35d27
Revises: 084eb2a102ec
Create Date: 2026-08-26 06:53:34.848580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4ed89e35d27'
down_revision: Union[str, Sequence[str], None] = '084eb2a102ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('stagione', sa.String(length=7), nullable=False),
    sa.Column('codice', sa.String(length=3), nullable=False),
    sa.Column('nome_completo', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('stagione', 'codice', name=op.f('pk_teams'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    # ### end Alembic commands ###
