"""voti + bonus_malus become one match_grain table

They were the same row twice. Measured before this was written
(``tasks/w4-proofs.out`` §2): 50,634 rows each, the key
``(stagione, giornata, nome)`` matches 50,634 for 50,634 with **zero orphans in
either direction**, and the six descriptor columns they share — ``data``,
``player_id``, ``ruolo``, ``ruolo_codice``, ``squadra_raw``, ``avversario_raw`` —
**disagree on zero rows**. The second copy of every descriptor, and a second copy of
all four indexes, stored nothing the first did not already say.

**The join key is the natural key, not the surrogate.** ``voti.id`` and
``bonus_malus.id`` are independent identity sequences and have never corresponded, so
joining on them would be silent nonsense. ``(stagione, giornata, nome)`` is what the
partial unique indexes already enforce on both sides.

**Nullability is preserved exactly, and it differs by half.** The six grade columns
stay nullable — a player can be ungraded, and a grade of zero is a real, terrible
grade. The ten counters stay NOT NULL. ``ora`` becomes nullable overall because
``bonus_malus`` never carried one.

**Reversible.** ``downgrade`` recreates both tables and splits the rows back, with
their indexes and constraints. What it cannot restore is the two original ``id``
sequences — they were surrogate, nothing referenced them, and no row is identified by
one. Every column anyone reads comes back.

Revision ID: b7d2f5a91c34
Revises: a1c4e77b3f01
Create Date: 2026-08-30
"""

from collections.abc import Sequence

from alembic import op

revision: str = "b7d2f5a91c34"
down_revision: str | Sequence[str] | None = "a1c4e77b3f01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_KEY = "v.stagione = b.stagione AND v.giornata = b.giornata AND v.nome = b.nome"

_GRADES = ("voto_fc", "fantavoto_fc", "voto_stat", "fantavoto_stat",
           "voto_italia", "fantavoto_italia")
_COUNTERS = ("ammonizione", "espulsione", "gol_segnati", "gol_subiti", "autoreti",
             "rigori_segnati", "rigori_sbagliati", "rigori_parati", "assist", "mvp")


def _partial_indexes(table: str) -> None:
    op.execute(
        f"CREATE UNIQUE INDEX uq_{table}_player ON {table} "
        f"(stagione, giornata, player_id) WHERE player_id IS NOT NULL"
    )
    op.execute(
        f"CREATE UNIQUE INDEX uq_{table}_coach ON {table} "
        f"(stagione, giornata, nome) WHERE player_id IS NULL"
    )
    op.execute(f"CREATE INDEX ix_{table}_stagione_giornata ON {table} (stagione, giornata)")


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE match_grain (
            id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
            stagione         VARCHAR(7)  NOT NULL,
            giornata         SMALLINT    NOT NULL,
            data             DATE        NOT NULL,
            ora              TIME,
            squadra_raw      VARCHAR(32) NOT NULL,
            avversario_raw   VARCHAR(32) NOT NULL,
            gol_squadra      SMALLINT    NOT NULL,
            gol_avversario   SMALLINT    NOT NULL,
            player_id        BIGINT,
            nome             TEXT        NOT NULL,
            ruolo_codice     VARCHAR(3)  NOT NULL,
            ruolo            TEXT        NOT NULL,
            voto_fc          NUMERIC(4,2),
            fantavoto_fc     NUMERIC(5,2),
            voto_stat        NUMERIC(4,2),
            fantavoto_stat   NUMERIC(5,2),
            voto_italia      NUMERIC(4,2),
            fantavoto_italia NUMERIC(5,2),
            ammonizione      SMALLINT    NOT NULL,
            espulsione       SMALLINT    NOT NULL,
            gol_segnati      SMALLINT    NOT NULL,
            gol_subiti       SMALLINT    NOT NULL,
            autoreti         SMALLINT    NOT NULL,
            rigori_segnati   SMALLINT    NOT NULL,
            rigori_sbagliati SMALLINT    NOT NULL,
            rigori_parati    SMALLINT    NOT NULL,
            assist           SMALLINT    NOT NULL,
            mvp              SMALLINT    NOT NULL,
            created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT pk_match_grain PRIMARY KEY (id),
            CONSTRAINT fk_match_grain_player_id_players
                FOREIGN KEY (player_id) REFERENCES players (id)
        )
        """
    )
    op.execute(
        f"""
        INSERT INTO match_grain (
            stagione, giornata, data, ora, squadra_raw, avversario_raw,
            gol_squadra, gol_avversario, player_id, nome, ruolo_codice, ruolo,
            {', '.join(_GRADES)}, {', '.join(_COUNTERS)}, created_at, updated_at
        )
        SELECT v.stagione, v.giornata, v.data, v.ora, v.squadra_raw, v.avversario_raw,
               v.gol_squadra, v.gol_avversario, v.player_id, v.nome, v.ruolo_codice,
               v.ruolo,
               {', '.join(f'v.{c}' for c in _GRADES)},
               {', '.join(f'b.{c}' for c in _COUNTERS)},
               LEAST(v.created_at, b.created_at), GREATEST(v.updated_at, b.updated_at)
        FROM voti v JOIN bonus_malus b ON {_KEY}
        """
    )
    _partial_indexes("match_grain")
    op.execute("DROP TABLE voti")
    op.execute("DROP TABLE bonus_malus")


def downgrade() -> None:
    op.execute(
        """
        CREATE TABLE voti (
            id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
            stagione         VARCHAR(7)  NOT NULL,
            giornata         SMALLINT    NOT NULL,
            data             DATE        NOT NULL,
            ora              TIME,
            squadra_raw      VARCHAR(32) NOT NULL,
            avversario_raw   VARCHAR(32) NOT NULL,
            gol_squadra      SMALLINT    NOT NULL,
            gol_avversario   SMALLINT    NOT NULL,
            player_id        BIGINT,
            nome             TEXT        NOT NULL,
            ruolo_codice     VARCHAR(3)  NOT NULL,
            ruolo            TEXT        NOT NULL,
            voto_fc          NUMERIC(4,2),
            fantavoto_fc     NUMERIC(5,2),
            voto_stat        NUMERIC(4,2),
            fantavoto_stat   NUMERIC(5,2),
            voto_italia      NUMERIC(4,2),
            fantavoto_italia NUMERIC(5,2),
            created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT pk_voti PRIMARY KEY (id),
            CONSTRAINT fk_voti_player_id_players FOREIGN KEY (player_id) REFERENCES players (id)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE bonus_malus (
            id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
            stagione         VARCHAR(7)  NOT NULL,
            giornata         SMALLINT    NOT NULL,
            data             DATE        NOT NULL,
            squadra_raw      VARCHAR(32) NOT NULL,
            avversario_raw   VARCHAR(32) NOT NULL,
            player_id        BIGINT,
            nome             TEXT        NOT NULL,
            ruolo_codice     VARCHAR(3)  NOT NULL,
            ruolo            TEXT        NOT NULL,
            ammonizione      SMALLINT    NOT NULL,
            espulsione       SMALLINT    NOT NULL,
            gol_segnati      SMALLINT    NOT NULL,
            gol_subiti       SMALLINT    NOT NULL,
            autoreti         SMALLINT    NOT NULL,
            rigori_segnati   SMALLINT    NOT NULL,
            rigori_sbagliati SMALLINT    NOT NULL,
            rigori_parati    SMALLINT    NOT NULL,
            assist           SMALLINT    NOT NULL,
            mvp              SMALLINT    NOT NULL,
            created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT pk_bonus_malus PRIMARY KEY (id),
            CONSTRAINT fk_bonus_malus_player_id_players
                FOREIGN KEY (player_id) REFERENCES players (id)
        )
        """
    )
    op.execute(
        f"""
        INSERT INTO voti (stagione, giornata, data, ora, squadra_raw, avversario_raw,
                          gol_squadra, gol_avversario, player_id, nome, ruolo_codice,
                          ruolo, {', '.join(_GRADES)}, created_at, updated_at)
        SELECT stagione, giornata, data, ora, squadra_raw, avversario_raw,
               gol_squadra, gol_avversario, player_id, nome, ruolo_codice, ruolo,
               {', '.join(_GRADES)}, created_at, updated_at
        FROM match_grain
        """
    )
    op.execute(
        f"""
        INSERT INTO bonus_malus (stagione, giornata, data, squadra_raw, avversario_raw,
                                 player_id, nome, ruolo_codice, ruolo,
                                 {', '.join(_COUNTERS)}, created_at, updated_at)
        SELECT stagione, giornata, data, squadra_raw, avversario_raw,
               player_id, nome, ruolo_codice, ruolo,
               {', '.join(_COUNTERS)}, created_at, updated_at
        FROM match_grain
        """
    )
    _partial_indexes("voti")
    _partial_indexes("bonus_malus")
    op.execute("DROP TABLE match_grain")
