"""add quotazioni table

Revision ID: befac71117d1
Revises: b4ed89e35d27
Create Date: 2026-08-26 06:56:29.299206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'befac71117d1'
down_revision: Union[str, Sequence[str], None] = 'b4ed89e35d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotazioni',
    sa.Column('stagione', sa.String(length=7), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('listone', sa.String(length=7), nullable=False),
    sa.Column('squadra', sa.String(length=3), nullable=False),
    sa.Column('ruoli_codice', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('ruoli', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('qi', sa.SmallInteger(), nullable=False),
    sa.Column('qa', sa.SmallInteger(), nullable=False),
    sa.Column('fvm', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("listone IN ('classic', 'mantra')", name=op.f('ck_quotazioni_listone')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_quotazioni_player_id_players')),
    sa.ForeignKeyConstraint(['stagione', 'squadra'], ['teams.stagione', 'teams.codice'], name=op.f('fk_quotazioni_stagione_squadra_teams')),
    sa.PrimaryKeyConstraint('stagione', 'player_id', 'listone', name=op.f('pk_quotazioni'))
    )
    op.create_index('ix_quotazioni_stagione_squadra', 'quotazioni', ['stagione', 'squadra'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quotazioni_stagione_squadra', table_name='quotazioni')
    op.drop_table('quotazioni')
    # ### end Alembic commands ###
