"""probe: array and partial unique indexes

Revision ID: c1a6360c049a
Revises: 
Create Date: 2026-08-26 06:36:27.365883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a6360c049a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_probe_match_grain',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('stagione', sa.String(length=7), nullable=False),
    sa.Column('giornata', sa.SmallInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('ruoli_codice', sa.ARRAY(sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__probe_match_grain'))
    )
    op.create_index('uq_probe_match_grain_coach', '_probe_match_grain', ['stagione', 'giornata', 'nome'], unique=True, postgresql_where=sa.text('player_id IS NULL'))
    op.create_index('uq_probe_match_grain_player', '_probe_match_grain', ['stagione', 'giornata', 'player_id'], unique=True, postgresql_where=sa.text('player_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_probe_match_grain_player', table_name='_probe_match_grain', postgresql_where=sa.text('player_id IS NOT NULL'))
    op.drop_index('uq_probe_match_grain_coach', table_name='_probe_match_grain', postgresql_where=sa.text('player_id IS NULL'))
    op.drop_table('_probe_match_grain')
    # ### end Alembic commands ###
