"""add match grain tables and retire the probe

Revision ID: ca3bb72a7a16
Revises: db5cb84620da
Create Date: 2026-08-26 07:04:10.871252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca3bb72a7a16'
down_revision: Union[str, Sequence[str], None] = 'db5cb84620da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonus_malus',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('stagione', sa.String(length=7), nullable=False),
    sa.Column('giornata', sa.SmallInteger(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('squadra_raw', sa.String(length=32), nullable=False),
    sa.Column('avversario_raw', sa.String(length=32), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('ruolo_codice', sa.String(length=3), nullable=False),
    sa.Column('ruolo', sa.Text(), nullable=False),
    sa.Column('ammonizione', sa.SmallInteger(), nullable=False),
    sa.Column('espulsione', sa.SmallInteger(), nullable=False),
    sa.Column('gol_segnati', sa.SmallInteger(), nullable=False),
    sa.Column('gol_subiti', sa.SmallInteger(), nullable=False),
    sa.Column('autoreti', sa.SmallInteger(), nullable=False),
    sa.Column('rigori_segnati', sa.SmallInteger(), nullable=False),
    sa.Column('rigori_sbagliati', sa.SmallInteger(), nullable=False),
    sa.Column('rigori_parati', sa.SmallInteger(), nullable=False),
    sa.Column('assist', sa.SmallInteger(), nullable=False),
    sa.Column('mvp', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_bonus_malus_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bonus_malus'))
    )
    op.create_index('ix_bonus_malus_stagione_giornata', 'bonus_malus', ['stagione', 'giornata'], unique=False)
    op.create_index('uq_bonus_malus_coach', 'bonus_malus', ['stagione', 'giornata', 'nome'], unique=True, postgresql_where=sa.text('player_id IS NULL'))
    op.create_index('uq_bonus_malus_player', 'bonus_malus', ['stagione', 'giornata', 'player_id'], unique=True, postgresql_where=sa.text('player_id IS NOT NULL'))
    op.create_table('voti',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('stagione', sa.String(length=7), nullable=False),
    sa.Column('giornata', sa.SmallInteger(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ora', sa.Time(), nullable=True),
    sa.Column('squadra_raw', sa.String(length=32), nullable=False),
    sa.Column('avversario_raw', sa.String(length=32), nullable=False),
    sa.Column('gol_squadra', sa.SmallInteger(), nullable=False),
    sa.Column('gol_avversario', sa.SmallInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('ruolo_codice', sa.String(length=3), nullable=False),
    sa.Column('ruolo', sa.Text(), nullable=False),
    sa.Column('voto_fc', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('fantavoto_fc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('voto_stat', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('fantavoto_stat', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('voto_italia', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('fantavoto_italia', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_voti_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voti'))
    )
    op.create_index('ix_voti_stagione_giornata', 'voti', ['stagione', 'giornata'], unique=False)
    op.create_index('uq_voti_coach', 'voti', ['stagione', 'giornata', 'nome'], unique=True, postgresql_where=sa.text('player_id IS NULL'))
    op.create_index('uq_voti_player', 'voti', ['stagione', 'giornata', 'player_id'], unique=True, postgresql_where=sa.text('player_id IS NOT NULL'))
    op.drop_index(op.f('uq_probe_match_grain_coach'), table_name='_probe_match_grain', postgresql_where='(player_id IS NULL)')
    op.drop_index(op.f('uq_probe_match_grain_player'), table_name='_probe_match_grain', postgresql_where='(player_id IS NOT NULL)')
    op.drop_table('_probe_match_grain')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_probe_match_grain',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('stagione', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('giornata', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('nome', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ruoli_codice', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__probe_match_grain'))
    )
    op.create_index(op.f('uq_probe_match_grain_player'), '_probe_match_grain', ['stagione', 'giornata', 'player_id'], unique=True, postgresql_where='(player_id IS NOT NULL)')
    op.create_index(op.f('uq_probe_match_grain_coach'), '_probe_match_grain', ['stagione', 'giornata', 'nome'], unique=True, postgresql_where='(player_id IS NULL)')
    op.drop_index('uq_voti_player', table_name='voti', postgresql_where=sa.text('player_id IS NOT NULL'))
    op.drop_index('uq_voti_coach', table_name='voti', postgresql_where=sa.text('player_id IS NULL'))
    op.drop_index('ix_voti_stagione_giornata', table_name='voti')
    op.drop_table('voti')
    op.drop_index('uq_bonus_malus_player', table_name='bonus_malus', postgresql_where=sa.text('player_id IS NOT NULL'))
    op.drop_index('uq_bonus_malus_coach', table_name='bonus_malus', postgresql_where=sa.text('player_id IS NULL'))
    op.drop_index('ix_bonus_malus_stagione_giornata', table_name='bonus_malus')
    op.drop_table('bonus_malus')
    # ### end Alembic commands ###
