"""asta_event: an integer key, three promoted columns, one fewer timestamp

381 MB and 486,803 rows, of which the payload was 489 bytes each and **38.6% of
those bytes were JSON keys** — the same handful, repeated on every row.

Three changes, each measured before it was written (``tasks/w4-proofs.out`` §3):

* **``asta_id`` → ``asta_key``.** A 36-character UUID stored 486,803 times over 224
  distinct auctions, in the heap and in both indexes. There is no in-place
  conversion: ``asta.id`` matches ``^[0-9]+$`` on 0 of 1,411 rows and is the FK
  target of ``asta_assignment``'s 43,298. So ``asta`` grew a surrogate ``key`` in
  the previous revision and this points at that.

* **Six keys leave the payload.** ``last_update`` and ``update_type`` were *already*
  columns and duplicated in the payload on every row with 0 mismatches and 0
  missing, so they are simply stripped. ``fantaleague_id`` moved to ``asta``, being
  strictly bijective with it. ``last_update_asta``, ``last_bid_time`` and
  ``timer_in_sec`` become typed columns: each carries a single JSON type across every
  row that has it, and no value has a decimal point, so ``BIGINT``/``BIGINT``/
  ``SMALLINT`` are exact rather than lossy (ranges 1.75e12–1.79e12, 1.79e12, and
  5–30).

* **``updated_at`` is dropped.** It differed from ``created_at`` on **0 rows** — this
  table is append-only. ``created_at`` stays: its lag from ``seen_at`` is a median
  7h55m, so it says when the loader wrote a row as against when the collector saw
  it, and nothing else holds that.

**CTAS and rename, not ALTER.** An ``UPDATE`` over 486,803 rows leaves the old
tuples behind and the table would need a ``VACUUM FULL`` to give the space back —
which is the entire point here. The cost is that everything implicit must be
restated: the identity default, both partial indexes, the foreign key. ``id`` is a
``SERIAL`` (``nextval('asta_event_id_seq')``), and a CTAS silently drops that
default, so the first ``insert(AstaEvent)`` that did not name ``id`` would fail NOT
NULL on an append-only archive. It is recreated here and the acceptance inserts
without naming ``id``.

**Reversible.** ``downgrade`` rebuilds the original shape and folds the promoted
columns back into the payload — the same expression ``AstaEvent.full_payload``
uses, which exists so the reconstruction is runnable outside a migration.

Revision ID: d3f81a6b2e50
Revises: ec89d795509f
Create Date: 2026-08-30
"""

from collections.abc import Sequence

from alembic import op

revision: str = "d3f81a6b2e50"
down_revision: str | Sequence[str] | None = "ec89d795509f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Stripped from the payload. The first three become columns; the last two were
#: already columns; `fantaleague_id` moved to `asta` in the previous revision.
_STRIPPED = (
    "last_update_asta",
    "last_bid_time",
    "timer_in_sec",
    "last_update",
    "update_type",
    "fantaleague_id",
)

_STRIP = " ".join(f"- '{k}'" for k in _STRIPPED)


def upgrade() -> None:
    op.execute(
        f"""
        CREATE TABLE asta_event_new (
            id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
            created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
            asta_key         BIGINT      NOT NULL,
            last_update      BIGINT,
            seen_at          TIMESTAMPTZ NOT NULL,
            update_type      TEXT,
            last_update_asta BIGINT,
            last_bid_time    BIGINT,
            timer_in_sec     SMALLINT,
            payload          JSONB       NOT NULL,
            CONSTRAINT pk_asta_event_new PRIMARY KEY (id)
        )
        """
    )
    op.execute(
        f"""
        INSERT INTO asta_event_new (
            id, created_at, asta_key, last_update, seen_at, update_type,
            last_update_asta, last_bid_time, timer_in_sec, payload
        )
        SELECT e.id,
               e.created_at,
               a.key,
               e.last_update,
               e.seen_at,
               e.update_type,
               (e.payload->>'last_update_asta')::bigint,
               (e.payload->>'last_bid_time')::bigint,
               (e.payload->>'timer_in_sec')::smallint,
               e.payload {_STRIP}
        FROM asta_event e JOIN asta a ON a.id = e.asta_id
        """
    )
    op.execute("DROP TABLE asta_event")
    op.execute("ALTER TABLE asta_event_new RENAME TO asta_event")
    op.execute("ALTER TABLE asta_event RENAME CONSTRAINT pk_asta_event_new TO pk_asta_event")

    # The identity a CTAS drops. Without this the first insert that does not name
    # `id` fails NOT NULL, on the one table that must never cost a record.
    op.execute(
        "SELECT setval(pg_get_serial_sequence('asta_event', 'id'), "
        "COALESCE((SELECT max(id) FROM asta_event), 1))"
    )
    op.execute(
        "ALTER TABLE asta_event ADD CONSTRAINT fk_asta_event_asta_key_asta "
        "FOREIGN KEY (asta_key) REFERENCES asta (key) ON DELETE CASCADE"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_asta_event_asta_key_last_update ON asta_event "
        "(asta_key, last_update) WHERE last_update IS NOT NULL"
    )
    op.execute(
        "CREATE INDEX ix_asta_event_asta_key_seen_at ON asta_event (asta_key, seen_at)"
    )


def downgrade() -> None:
    op.execute(
        """
        CREATE TABLE asta_event_old (
            id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
            asta_id     TEXT        NOT NULL,
            last_update BIGINT,
            seen_at     TIMESTAMPTZ NOT NULL,
            update_type TEXT,
            payload     JSONB       NOT NULL,
            created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT pk_asta_event_old PRIMARY KEY (id)
        )
        """
    )
    # Fold the promoted columns back in. `updated_at` cannot be restored — it was
    # always equal to `created_at`, so it is rebuilt from it, which is what it held.
    op.execute(
        """
        INSERT INTO asta_event_old (id, asta_id, last_update, seen_at, update_type,
                                    payload, created_at, updated_at)
        SELECT e.id, a.id, e.last_update, e.seen_at, e.update_type,
               e.payload
                 || jsonb_strip_nulls(jsonb_build_object(
                        'last_update_asta', e.last_update_asta,
                        'last_bid_time',    e.last_bid_time,
                        'timer_in_sec',     e.timer_in_sec,
                        'last_update',      e.last_update,
                        'update_type',      e.update_type,
                        'fantaleague_id',   a.fantaleague_id)),
               e.created_at,
               -- `updated_at` was equal to `created_at` on all 486,803 rows, which
               -- is why it was dropped. Restoring it from `created_at` restores what
               -- it held, not an approximation of it.
               e.created_at
        FROM asta_event e JOIN asta a ON a.key = e.asta_key
        """
    )
    op.execute("DROP TABLE asta_event")
    op.execute("ALTER TABLE asta_event_old RENAME TO asta_event")
    op.execute("ALTER TABLE asta_event RENAME CONSTRAINT pk_asta_event_old TO pk_asta_event")
    op.execute(
        "SELECT setval(pg_get_serial_sequence('asta_event', 'id'), "
        "COALESCE((SELECT max(id) FROM asta_event), 1))"
    )
    op.execute(
        "ALTER TABLE asta_event ADD CONSTRAINT fk_asta_event_asta_id_asta "
        "FOREIGN KEY (asta_id) REFERENCES asta (id) ON DELETE CASCADE"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_asta_event_asta_id_last_update ON asta_event "
        "(asta_id, last_update) WHERE last_update IS NOT NULL"
    )
    op.execute(
        "CREATE INDEX ix_asta_event_asta_id_seen_at ON asta_event (asta_id, seen_at)"
    )
