"""add target_price table

Revision ID: db5cb84620da
Revises: 2c01d7f58c06
Create Date: 2026-08-26 07:02:05.737794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db5cb84620da'
down_revision: Union[str, Sequence[str], None] = '2c01d7f58c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target_price',
    sa.Column('stagione', sa.String(length=7), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('listone', sa.String(length=7), nullable=False),
    sa.Column('squadra', sa.String(length=3), nullable=False),
    sa.Column('ruoli_codice', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('macro_role', sa.String(length=8), nullable=False),
    sa.Column('qi', sa.SmallInteger(), nullable=False),
    sa.Column('prior_media_fantavoto', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('predicted_pct_delta', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('team_factor', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('target_price', sa.SmallInteger(), nullable=False),
    sa.Column('flags', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("listone IN ('classic', 'mantra')", name=op.f('ck_target_price_listone')),
    sa.CheckConstraint('flags IS NOT NULL', name=op.f('ck_target_price_flags_not_null')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_target_price_player_id_players')),
    sa.ForeignKeyConstraint(['stagione', 'squadra'], ['teams.stagione', 'teams.codice'], name=op.f('fk_target_price_stagione_squadra_teams')),
    sa.PrimaryKeyConstraint('stagione', 'player_id', 'listone', name=op.f('pk_target_price'))
    )
    op.create_index('ix_target_price_stagione_macro', 'target_price', ['stagione', 'macro_role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_target_price_stagione_macro', table_name='target_price')
    op.drop_table('target_price')
    # ### end Alembic commands ###
