"""lega sync: rosters, competitions, calendar, custom roles

Revision ID: e35dbc3294a7
Revises: 5839418913d5
Create Date: 2026-09-02 20:41:07.755394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35dbc3294a7'
down_revision: Union[str, Sequence[str], None] = '5839418913d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_competition',
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=False),
    sa.Column('competition_id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('tipo', sa.SmallInteger(), nullable=True),
    sa.Column('start_day', sa.SmallInteger(), nullable=True),
    sa.Column('end_day', sa.SmallInteger(), nullable=True),
    sa.Column('team_ids', sa.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('captured_at', 'league_id', 'competition_id', name=op.f('pk_league_competition'))
    )
    op.create_table('league_custom_role',
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('club', sa.Text(), nullable=False),
    sa.Column('original_role', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('captured_at', 'league_id', 'player_id', name=op.f('pk_league_custom_role'))
    )
    op.create_table('league_fixture',
    sa.Column('competition_id', sa.BigInteger(), nullable=False),
    sa.Column('matchday', sa.SmallInteger(), nullable=False),
    sa.Column('team_home', sa.BigInteger(), nullable=False),
    sa.Column('team_away', sa.BigInteger(), nullable=False),
    sa.Column('championship_matchday', sa.SmallInteger(), nullable=True),
    sa.Column('points_home', sa.Float(), nullable=True),
    sa.Column('points_away', sa.Float(), nullable=True),
    sa.Column('standing_home', sa.SmallInteger(), nullable=True),
    sa.Column('standing_away', sa.SmallInteger(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('real_result', sa.Text(), nullable=True),
    sa.Column('calculated', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('competition_id', 'matchday', 'team_home', 'team_away', name=op.f('pk_league_fixture'))
    )
    op.add_column('league_snapshot', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('league_snapshot', sa.Column('stopped', sa.Boolean(), nullable=True))
    op.add_column('league_snapshot', sa.Column('role_groups', sa.SmallInteger(), nullable=True))
    op.add_column('league_snapshot', sa.Column('min_roles', sa.ARRAY(sa.SmallInteger()), nullable=True))
    op.add_column('league_snapshot', sa.Column('max_roles', sa.ARRAY(sa.SmallInteger()), nullable=True))
    op.add_column('league_snapshot', sa.Column('modules', sa.ARRAY(sa.Text()), nullable=True))
    op.add_column('league_snapshot', sa.Column('bench_size', sa.SmallInteger(), nullable=True))
    op.add_column('league_snapshot', sa.Column('captain_slots', sa.SmallInteger(), nullable=True))
    op.add_column('league_team_snapshot', sa.Column('division', sa.Text(), nullable=True))
    op.add_column('league_team_snapshot', sa.Column('roster_ids', sa.ARRAY(sa.BigInteger()), nullable=True))
    op.add_column('league_team_snapshot', sa.Column('roster_costs', sa.ARRAY(sa.SmallInteger()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league_team_snapshot', 'roster_costs')
    op.drop_column('league_team_snapshot', 'roster_ids')
    op.drop_column('league_team_snapshot', 'division')
    op.drop_column('league_snapshot', 'captain_slots')
    op.drop_column('league_snapshot', 'bench_size')
    op.drop_column('league_snapshot', 'modules')
    op.drop_column('league_snapshot', 'max_roles')
    op.drop_column('league_snapshot', 'min_roles')
    op.drop_column('league_snapshot', 'role_groups')
    op.drop_column('league_snapshot', 'stopped')
    op.drop_column('league_snapshot', 'active')
    op.drop_table('league_fixture')
    op.drop_table('league_custom_role')
    op.drop_table('league_competition')
    # ### end Alembic commands ###
