"""asta gains a surrogate key and fantaleague_id

Both exist so `asta_event` can stop carrying them 486,803 times.

**`key`** is a surrogate. `id` stays the primary key — it is the platform's own
UUID, `asta_assignment`'s 43,298 rows reference it, and it is what a human matches
against FantaLab. `asta_event.asta_id` becomes an integer pointing at `key` in the
next revision. Measured: `asta.id` is 36 characters on all 1,411 rows and matches
`^[0-9]+$` on none, so there is no in-place conversion to make.

**`fantaleague_id`** is lifted out of every event payload, where it was measured
strictly bijective with `asta_id` — 0 auctions under two leagues, 0 leagues under
two auctions, across 486,803 rows and 224 distinct values (`tasks/w4-proofs.out`
§3d). Storing it per event was 486,803 copies of 224 facts.

It is backfilled from the payloads here, which is the only place that mapping
exists. Auctions with no observed event keep NULL — 1,411 rows in `asta`, 224 of
them ever observed.

**The `upsert_auctions` exclusion set is fixed in the same commit**, and has to be:
that method builds its `ON CONFLICT SET` by iterating the model, so both new columns
would be enrolled automatically and set to NULL by `auction_rows`, which supplies
neither. `harvest load` calls it before `upsert_events` on every ten-second pass —
the key would be renumbered under the events pointing at it and the league blanked,
continuously and silently, on a green suite.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec89d795509f'
down_revision: Union[str, Sequence[str], None] = 'b7d2f5a91c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asta', sa.Column('key', sa.BigInteger(), sa.Identity(always=False), nullable=False))
    op.add_column('asta', sa.Column('fantaleague_id', sa.Text(), nullable=True))
    op.create_unique_constraint(op.f('uq_asta_key'), 'asta', ['key'])
    # ### end Alembic commands ###

    # Backfill from the payloads — the only place that mapping exists. DISTINCT is
    # safe because the bijection was verified before this was written: 0 auctions
    # under two leagues, 0 leagues under two auctions.
    op.execute(
        """
        UPDATE asta a
           SET fantaleague_id = e.fl
          FROM (SELECT DISTINCT asta_id, payload->>'fantaleague_id' AS fl
                  FROM asta_event
                 WHERE payload ? 'fantaleague_id') e
         WHERE e.asta_id = a.id
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_asta_key'), 'asta', type_='unique')
    op.drop_column('asta', 'fantaleague_id')
    op.drop_column('asta', 'key')
    # ### end Alembic commands ###
