#!/usr/bin/env bash
# The standing gate. Every check, in order, and a non-zero exit if any of them fails.
#
# This exists because the gate kept being run as a `&&` chain with each command piped
# into `tail`, and a pipeline's status is its *last* command's -- so `pytest | tail -1`
# exits 0 with a failing suite and the chain continues. That masked a real failure three
# times, once past a commit. Nothing here is piped.
#
# Every pytest run below names `tests/`. It used to be the only thing standing between
# the gate and a root run that collected `app/fantabot_app/api/tests` and
# `app/tests/test_server.py` -- a different interpreter's suite, importing fastapi, which
# the conda `fanta` env does not have. The root `pyproject.toml` now sets
# `testpaths = ["tests"]`, so a bare `python -m pytest` does the right thing on its own and
# this scoping is belt to that braces. It stays because it is free and because it says, at
# the point of use, which suite the gate is: the app's own is `cd app && uv run pytest`.
# The objection that kept `testpaths` unset -- that it would silence the `integration`/
# `e2e` marker declarations -- was real and is answered in `pyproject.toml`: those markers
# are the app's, `tests/` never uses them, and they are declared for the runs that still
# name an app path explicitly.
#
# Usage: scripts/gate.sh [--fast]   (--fast skips the db tier and alembic)
set -uo pipefail

fast=0
[[ ${1:-} == "--fast" ]] && fast=1

failed=()
run() {
    local name=$1; shift
    printf '\n=== %s ===\n' "$name"
    if "$@"; then
        printf '  ok\n'
    else
        printf '  FAILED (exit %d)\n' "$?"
        failed+=("$name")
    fi
}

run "unit tests"    python -m pytest -q tests/
run "ruff"          ruff check src tests
run "mypy"          mypy
run "golden"        python -m pytest -q tests/test_golden.py

# Golden files are regenerated by the run above only under FANTABOT_GOLDEN_UPDATE; a
# diff here means the recorded output moved without anyone recording it.
printf '\n=== golden files unchanged ===\n'
if [[ -z "$(git status --porcelain tests/golden/)" ]]; then
    printf '  ok\n'
else
    printf '  FAILED — tests/golden/ is dirty:\n'
    git status --porcelain tests/golden/
    failed+=("golden files unchanged")
fi

if (( ! fast )); then
    run "db tier"   python -m pytest -q -m db tests/
    run "alembic"   alembic check
fi

printf '\n'
if (( ${#failed[@]} )); then
    printf 'GATE RED: %s\n' "${failed[*]}"
    exit 1
fi
printf 'GATE GREEN\n'
